remote_theme: fluffyemily/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "fp-ts on GitHub":
      - "//github.com/gcanti/fp-ts"
